// <auto-generated />
using System;
using AnSinh360.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AnSinh360.Infrastructure.Migrations
{
    [DbContext(typeof(DatasetDbContext))]
    [Migration("20261004071648_InitialDataset")]
    partial class InitialDataset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dataset")
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AnSinh360.Domain.DatasetMetadata", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("dataset_metadata", "dataset");
                });

            modelBuilder.Entity("AnSinh360.Domain.DatasetTestCase", b =>
                {
                    b.Property<string>("TestId")
                        .HasColumnType("text")
                        .HasColumnName("test_id");

                    b.Property<string>("ExpectedMissingFields")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("expected_missing_fields");

                    b.Property<string>("ExpectedPolicies")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("expected_policies");

                    b.Property<string>("ExpectedResult")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("expected_result");

                    b.Property<string>("ExpectedServices")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("expected_services");

                    b.Property<string>("InputSummary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("input_summary");

                    b.Property<string>("Journey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("journey");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("TestId");

                    b.ToTable("dataset_test_cases", "dataset");
                });

            modelBuilder.Entity("AnSinh360.Domain.EnumDefinition", b =>
                {
                    b.Property<string>("EnumGroup")
                        .HasColumnType("text")
                        .HasColumnName("enum_group");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.Property<string>("Active")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("active");

                    b.Property<string>("LabelVi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label_vi");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("meaning");

                    b.HasKey("EnumGroup", "Value");

                    b.ToTable("enum_definitions", "dataset");
                });

            modelBuilder.Entity("AnSinh360.Domain.LifeEvent", b =>
                {
                    b.Property<string>("LifeEventId")
                        .HasColumnType("text")
                        .HasColumnName("life_event_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PrimaryDemo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("primary_demo");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("LifeEventId");

                    b.ToTable("life_events", "dataset");
                });

            modelBuilder.Entity("AnSinh360.Domain.OfficialSource", b =>
                {
                    b.Property<string>("SourceId")
                        .HasColumnType("text")
                        .HasColumnName("source_id");

                    b.Property<string>("ArchiveStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("archive_status");

                    b.Property<string>("CanonicalUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("canonical_url");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("document_number");

                    b.Property<string>("EffectiveFrom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("effective_from");

                    b.Property<string>("EffectiveTo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("effective_to");

                    b.Property<string>("IssuingAuthority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("issuing_authority");

                    b.Property<string>("Journey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("journey");

                    b.Property<string>("LastVerifiedAt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_verified_at");

                    b.Property<string>("LegalStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("legal_status");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PublishedAt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("published_at");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("publisher");

                    b.Property<string>("SourceLevel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_level");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_type");

                    b.Property<string>("SupersededBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("superseded_by");

                    b.Property<string>("Supersedes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("supersedes");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("verification_status");

                    b.HasKey("SourceId");

                    b.HasIndex("VerificationStatus");

                    b.ToTable("sources", "dataset");
                });

            modelBuilder.Entity("AnSinh360.Domain.Opportunity", b =>
                {
                    b.Property<string>("OpportunityId")
                        .HasColumnType("text")
                        .HasColumnName("opportunity_id");

                    b.Property<string>("Capacity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("capacity");

                    b.Property<string>("LastVerified")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_verified");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("OpenFrom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("open_from");

                    b.Property<string>("OpenUntil")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("open_until");

                    b.Property<string>("PolicyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("policy_id");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_id");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("OpportunityId");

                    b.HasIndex("PolicyId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("SourceId");

                    b.HasIndex("Status");

                    b.ToTable("opportunities", "dataset");
                });

            modelBuilder.Entity("AnSinh360.Domain.Policy", b =>
                {
                    b.Property<string>("PolicyId")
                        .HasColumnType("text")
                        .HasColumnName("policy_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("EffectiveFrom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("effective_from");

                    b.Property<string>("EffectiveTo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("effective_to");

                    b.Property<string>("Journey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("journey");

                    b.Property<string>("LastVerified")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_verified");

                    b.Property<string>("LegalSourceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("legal_source_id");

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("policy_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("TargetGroup")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_group");

                    b.HasKey("PolicyId");

                    b.HasIndex("LegalSourceId");

                    b.ToTable("policies", "dataset");
                });

            modelBuilder.Entity("AnSinh360.Domain.PolicyRule", b =>
                {
                    b.Property<string>("RuleId")
                        .HasColumnType("text")
                        .HasColumnName("rule_id");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field");

                    b.Property<string>("LogicConnector")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("logic_connector");

                    b.Property<string>("MatchReason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("match_reason");

                    b.Property<string>("MissingReason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("missing_reason");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operator");

                    b.Property<string>("PolicyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("policy_id");

                    b.Property<string>("Required")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("required");

                    b.Property<string>("RuleGroup")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rule_group");

                    b.Property<string>("SourceArticle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_article");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("verification_status");

                    b.HasKey("RuleId");

                    b.HasIndex("Field");

                    b.HasIndex("PolicyId");

                    b.HasIndex("SourceId");

                    b.ToTable("policy_rules", "dataset");
                });

            modelBuilder.Entity("AnSinh360.Domain.PolicyServiceMap", b =>
                {
                    b.Property<string>("MapId")
                        .HasColumnType("text")
                        .HasColumnName("map_id");

                    b.Property<string>("Intent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("intent");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PolicyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("policy_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_id");

                    b.HasKey("MapId");

                    b.HasIndex("PolicyId");

                    b.HasIndex("ServiceId");

                    b.ToTable("policy_service_maps", "dataset");
                });

            modelBuilder.Entity("AnSinh360.Domain.ProfileField", b =>
                {
                    b.Property<string>("FieldId")
                        .HasColumnType("text")
                        .HasColumnName("field_id");

                    b.Property<string>("AllowedValues")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("allowed_values");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data_type");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field_name");

                    b.Property<string>("Journey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("journey");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PersistDefault")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("persist_default");

                    b.Property<string>("QuestionVi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_vi");

                    b.Property<string>("RequiredWhen")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("required_when");

                    b.Property<string>("Sensitivity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sensitivity");

                    b.Property<string>("SourceRuleIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_rule_ids");

                    b.HasKey("FieldId");

                    b.HasIndex("FieldName");

                    b.ToTable("profile_fields", "dataset");
                });

            modelBuilder.Entity("AnSinh360.Domain.Service", b =>
                {
                    b.Property<string>("ServiceId")
                        .HasColumnType("text")
                        .HasColumnName("service_id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Fee")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fee");

                    b.Property<string>("FreshnessRule")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("freshness_rule");

                    b.Property<string>("Journey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("journey");

                    b.Property<string>("LastVerified")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_verified");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("OnlineUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("online_url");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("ProcedureCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("procedure_code");

                    b.Property<string>("ProcessingTime")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("processing_time");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("ResultOrAction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("result_or_action");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_name");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_type");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("SubmissionChannels")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("submission_channels");

                    b.Property<string>("SupportedIntents")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("supported_intents");

                    b.HasKey("ServiceId");

                    b.HasIndex("SourceId");

                    b.ToTable("services", "dataset");
                });

            modelBuilder.Entity("AnSinh360.Domain.ServiceChecklist", b =>
                {
                    b.Property<string>("ChecklistId")
                        .HasColumnType("text")
                        .HasColumnName("checklist_id");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("condition");

                    b.Property<string>("DocumentOrStep")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("document_or_step");

                    b.Property<string>("ItemOrder")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_order");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Required")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("required");

                    b.Property<string>("RequirementType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("requirement_type");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_id");

                    b.Property<string>("SourceDetail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_detail");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_id");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("verification_status");

                    b.HasKey("ChecklistId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("SourceId");

                    b.ToTable("service_checklists", "dataset");
                });

            modelBuilder.Entity("AnSinh360.Domain.ServiceRule", b =>
                {
                    b.Property<string>("RuleId")
                        .HasColumnType("text")
                        .HasColumnName("rule_id");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("condition");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event");

                    b.Property<string>("Intent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("intent");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("RuleId");

                    b.HasIndex("ServiceId");

                    b.ToTable("service_rules", "dataset");
                });

            modelBuilder.Entity("AnSinh360.Domain.VerificationLog", b =>
                {
                    b.Property<string>("LogId")
                        .HasColumnType("text")
                        .HasColumnName("log_id");

                    b.Property<string>("CheckedAt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("checked_at");

                    b.Property<string>("CheckedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("checked_by");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_id");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("verification_status");

                    b.HasKey("LogId");

                    b.HasIndex("SourceId");

                    b.ToTable("verification_logs", "dataset");
                });

            modelBuilder.Entity("AnSinh360.Infrastructure.ImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CountsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("counts");

                    b.Property<string>("DatasetVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dataset_version");

                    b.Property<string>("FileHashesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("file_hashes");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("fingerprint");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at");

                    b.HasKey("Id");

                    b.HasIndex("Fingerprint");

                    b.ToTable("import_batches", "dataset");
                });

            modelBuilder.Entity("AnSinh360.Domain.Opportunity", b =>
                {
                    b.HasOne("AnSinh360.Domain.Policy", null)
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnSinh360.Domain.Service", null)
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnSinh360.Domain.OfficialSource", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AnSinh360.Domain.Policy", b =>
                {
                    b.HasOne("AnSinh360.Domain.OfficialSource", null)
                        .WithMany()
                        .HasForeignKey("LegalSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AnSinh360.Domain.PolicyRule", b =>
                {
                    b.HasOne("AnSinh360.Domain.Policy", null)
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnSinh360.Domain.OfficialSource", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AnSinh360.Domain.PolicyServiceMap", b =>
                {
                    b.HasOne("AnSinh360.Domain.Policy", null)
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnSinh360.Domain.Service", null)
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AnSinh360.Domain.Service", b =>
                {
                    b.HasOne("AnSinh360.Domain.OfficialSource", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AnSinh360.Domain.ServiceChecklist", b =>
                {
                    b.HasOne("AnSinh360.Domain.Service", null)
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnSinh360.Domain.OfficialSource", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AnSinh360.Domain.ServiceRule", b =>
                {
                    b.HasOne("AnSinh360.Domain.Service", null)
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
